services:

  db:
    image: mysql:latest
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
  app:
    image: phpmyadmin:latest
    container_name: phpmyadmin-rifive-laravel
    ports:
        - 8080:80
    links:
        - db
    #restart: unless-stopped
    restart : always
    environment:
        #PMA_HOST: db
        #PMA_USER: root
        #PMA_PASSWORD: root
        #PMA_PORT: 3306
        PMA_ARBITRARY: 1
    depends_on:
        - db
    volumes:
      - ./php-make/upload.ini:/usr/local/etc/php/php.ini
