version: '3.8'
services:
  db:
    image: mysql:latest
    #restart: always
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_USER: 'laravel_user'
      MYSQL_PASSWORD: 'Laravel'
      MYSQL_ROOT_PASSWORD: 'Laravel'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 13306:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./php-make/upload.ini:/usr/local/etc/php/php.ini
volumes:
  my-db:
